[tool.poetry]
name = "sir-robin"
version = "0.1.0"
description = ""
authors = ["Python Discord <info@pythondiscord.com>"]

[tool.poetry.dependencies]
python = "^3.9"
disnake = "^2.4.0"
flake8 = "^4.0.1"
flake8-annotations = "^2.7.0"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
flake8-isort = "^4.1.1"
flake8-string-format = "^0.3.0"
flake8-tidy-imports = "^4.6.0"
flake8-todo = "^0.7"
pep8-naming = "^0.12.1"
pre-commit = "^2.17.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
